src/main/java/com/biz/lesson/model/config/Config.java
package com.biz.lesson.model.config;

import java.util.Map;
import java.util.Properties;

import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.biz.lesson.util.JsonUtil;

/**
 * 系统配置
 */
public final class Config {

    private static final Logger logger = LoggerFactory.getLogger(Config.class);

    private Properties properties = new Properties();

    private static volatile Config instance;

    private Config() {
    }

    public static Config getInstance() {
        if (instance == null) {
            synchronized (Config.class) {
                if (instance == null) {
                    instance = new Config();
                }
            }
        }
        return instance;
    }

    public void clear() {
        properties.clear();
    }

    public void putAll(Map<String, String> t) {
        properties.putAll(t);
    }

    public void putAll(Properties p) {
        properties.putAll(p);
    }

    public void put(String key, String value) {
        properties.put(key, value);
    }

    public int size() {
        return properties.size();
    }


    public Properties getProperties() {
        return properties;
    }

    public Integer getInt(String key, int defaultValue) {
        Integer result = defaultValue;
        try {
            result = Integer.valueOf(get(key));
        } catch (Exception e) {
        }
        return result;
    }

    public String getHostNamePostfix() {
        return StringUtils.defaultIfEmpty(properties.getProperty("host_name_postfix"), ".cn");
    }

    public String get(String key) {
        String value = properties.getProperty(key + getHostNamePostfix());
        if (StringUtils.isBlank(value)) {
            value = properties.getProperty(key);
        }
        return value;
    }


    public String get(String key, String defaultValue) {
        String value = properties.getProperty(key + getHostNamePostfix());
        if (StringUtils.isBlank(value)) {
            value = properties.getProperty(key, defaultValue);
        }
        return value;
    }

    /**
     * google 地图使用的域名
     */
    public String getGoogleApiHostName() {
        return get("google_api_domain_name", "maps.google.cn");
    }

    /**
     * googlemap API Key
     */
    public String getGoogleApiKey() {
        return get("google_map_key", "屏蔽");
    }

    /**
     * 邮件server
     */
    public String getMailServer() {
        return properties.getProperty("default_mail_server");
    }

    /**
     * 默认发件人密码
     */
    public String getMailPassword() {
        return properties.getProperty("default_mail_password");
    }

    public String getMailAddress() {
        return properties.getProperty("default_mail_address");
    }

    /**
     * 是否启动发送邮件线程
     */
    public boolean getSendMail() {
        return StringUtils.equalsIgnoreCase(get("send_mail", "true"), "true");
    }

    /**
     * 是否允许一个账号多个浏览器同时登陆系统
     */
    public boolean getAllowMultipleLogin() {
        return StringUtils.equalsIgnoreCase(get("allow_multiple_login"), "true");
    }



    /**
     * tomcat启动端口
     */
    public String getHttpPort() {
        if (isProxy()) {
            return "";
        } else {
            return ":" + properties.getProperty("http_port");
        }
    }

    /**
     * context_path
     */
    public String getContextPath() {
        return properties.getProperty("context_path");
    }

    /**
     * 创建邮件使用的http前缀
     */
    public String getCreateMailHttpPrefix() {
        return "http://127.0.0.1" + getHttpPort() + getContextPath();
    }

    /**
     * 系统域名
     */
    public String getDomain() {
        return get("domain");
    }

    public String getEmailRefererHost() {
        return "http://" + get("domain.net") + getHttpPort() + getContextPath();
    }

    public String getDocRefererHost() {
        return "http://" + get("domain.cn") + getHttpPort() + getContextPath();
    }


    /**
     * 邮件中给出的对外连接的http前缀
     */
    public String getOutUrlPrefix() {
        return "http://" + getDomain() + getHttpPort() + getContextPath();
    }


    public Boolean getAccessLogSaveSync() {
        return StringUtils.equalsIgnoreCase(get("access_log_save_sync", "true"), "true");
    }


    /**
     * 七牛空间名称
     */
    public String getQiNiuBucket() {
        return get("qiniu.bucket");
    }

    /**
     * 七牛Access Key
     */
    public String getQiNiuAK() {
        return get("qiniu.ak");
    }

    /**
     * 七牛Secret Key
     */
    public String getQiNiuSK() {
        return get("qiniu.sk");
    }

    /**
     * 七牛空间访问域名
     */
    public String getQiNiuDomain() {
        return get("qiniu.domain");
    }


    public String getHttpProtocol() {
        return get("http_protocol", "http");
    }

    public String[] getSMTPServers() {
        return StringUtils.split(get("send_smtp_servers"), ",");
    }

    public boolean isProxy() {
        return StringUtils.equalsIgnoreCase(get("nginx_proxy"), "true");
    }

    public String getCodeServiceUrl() {
        return get("code_service_url");
    }

    public String getSystemLogo() {
        return get("system_logo", "login_1.jpg");
    }

	
	public <T> T getJsonObject(String key,Class<T> t){
		String value = this.get(key);
		return JsonUtil.json2Obj(value, t);
	}

}

src/main/java/com/biz/lesson/model/stu/Lession.java
package com.biz.lesson.model.stu;

import javax.persistence.*;
import java.util.Set;

/**
 * @author kevin zhao
 * @date 2018/7/25
 */
@Table(name = "lession")
@Entity
public class Lession {
    @Id
    @GeneratedValue
    private Integer id;
    @Column(name = "sub_name")
    private String subName;
    @Column(name = "per_Num")
    private Integer perNum;
    private Float score;


    @ManyToMany(mappedBy = "lessions")
    private Set<Stu> stus;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSubName() {
        return subName;
    }

    public void setSubName(String subName) {
        this.subName = subName;
    }

    public Float getScore() {
        return score;
    }

    public void setScore(Float score) {
        this.score = score;
    }

    public Set<Stu> getStus() {
        return stus;
    }

    public void setStus(Set<Stu> stus) {
        this.stus = stus;
    }

    public Integer getPerNum() {
        return perNum;
    }

    public void setPerNum(Integer perNum) {
        this.perNum = perNum;
    }

    @Override
    public String toString() {
        return "Lession{" +
                "id=" + id +
                ", subName='" + subName + '\'' +
                ", perNum=" + perNum +
                ", score=" + score +
                '}';
    }
}

src/main/java/com/biz/lesson/web/controller/stu/LessionController.java
package com.biz.lesson.web.controller.stu;

import com.biz.lesson.Constants;
import com.biz.lesson.business.stu.LessionSerivce;
import com.biz.lesson.model.stu.Lession;
import com.biz.lesson.util.Layui;
import com.biz.lesson.util.ReturnValueMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import sun.rmi.runtime.Log;

import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.Map;

/**
 * @author kevin zhao
 * @date 2018/7/28
 */
@Controller
@RequestMapping(value = "/lession")
public class LessionController {

    @Autowired
    private LessionSerivce lessionSerivce;
    @Autowired
    private HttpServletRequest request;
    private static final Logger logger = LoggerFactory.getLogger(LessionController.class);


    @RequestMapping(value = "/to/{id}/{flag}")
    public String to(@PathVariable("id") Integer id, @PathVariable("flag") String flag) {
        if (flag.trim().equals(Constants.LIST)) {
            return "kevin/lession/list";
        }
        if (flag.trim().equals(Constants.ADD)) {
            return "kevin/lession/add";
        }
        if (flag.trim().equals(Constants.EDIT)) {
            Lession lession = lessionSerivce.findById(id);
            request.setAttribute("lession", lession);
            return "kevin/lession/modify";
        }
        return null;
    }

    @RequestMapping(value = "/list")
    @ResponseBody
    public Layui list(Integer page, Integer limit) {
        Page<Lession> lessionPage = lessionSerivce.findByPage(page, limit);
        return Layui.data((int) lessionPage.getTotalElements(), lessionPage.getContent());
    }

    @RequestMapping(value = "/add", method = RequestMethod.POST)
    @ResponseBody
    public Map<Object, Object> add(Lession lession) {
        Map<Object, Object> map = new HashMap<>();
        try {
            lessionSerivce.add(lession);
            map.put("code", 200);
            map.put("msg", "保存成功");
        } catch (Exception e) {
            map.put("code", 400);
            map.put("msg", "保存失败");
        }
        return map;
    }

    @RequestMapping(value = "/modify", method = RequestMethod.PUT)
    @ResponseBody
    public Map<Object, Object> modify(Lession lession) {
        Map<Object, Object> map = new HashMap<>();
        try {
            lessionSerivce.modify(lession);
            logger.debug("modify");
            map.put("code", 200);
            map.put("msg", "修改成功");
        } catch (Exception e) {
            map.put("code", 400);
            map.put("msg", "修改失败");
        }
        return map;
    }

    @ResponseBody
    @RequestMapping(value = "/del", method = RequestMethod.DELETE)
    public Map<Object, Object> del(Integer id) {
        Map<Object, Object> map = new HashMap<>();
        try {
            lessionSerivce.del(id);
            map.put("code", 200);
            map.put("msg", "删除成功");
        } catch (Exception e) {
            map.put("code", 400);
            map.put("msg", "删除失败");
        }
        return map;
    }
}

src/main/webapp/WEB-INF/views/kevin/lession/add.jsp
<%--
  Created by IntelliJ IDEA.
  User: Administrator
  Date: 2018/7/26
  Time: 13:40
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="bizLesson" uri="http://com.biz.lesson/tag/core" %>
<%@ taglib prefix="lesson" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>欢迎使用 LESSION 6</title>
    <link rel="stylesheet" href="${pageContext.servletContext.contextPath}/webjars/layui/2.3.0/css/layui.css">
    <script language="JavaScript"
            src="${pageContext.servletContext.contextPath}/webjars/layui/2.3.0/layui.all.js"></script>
</head>
<body>
<lesson:page title="">
<jsp:attribute name="script">
        <script language="JavaScript">
            $(function () {
                layui.use(["upload", "form"], function () {
                    var $upload = layui.upload;
                    var $form = layui.form;
                    $form.render();

                    $form.verify({
                        subName: function (value, item) {
                            if (value.trim() === "") {
                                return "课程名称不能为空"
                            }
                        },
                    });

                    $form.on("submit(add)", function (data) {
                        $.ajax({
                            url: data.form.action,
                            type: data.form.method,
                            data: data.field,
                            dataType: "json",
                            success: function (res) {
                                console.log(res);
                                if (res.code === 400) {
                                }
                                if (res.code === 200) {
                                    window.location.href = "${pageContext.servletContext.contextPath}/lession/to/0/list.do";
                                }
                            }
                        });
                        return false;
                    });
                });
            });
        </script>
    </jsp:attribute>

<jsp:body>
<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="welcome.do"><spring:message code="common.homepage"/></a>
        </li>

        <li class="active"><spring:message code="lession.title.add"/></li>
    </ul>
</div>
<br><br>
<div class="container">
    <div id="user-profile-1" class="user-profile row">

        <div class="col-sm-9">
            <form class="form-horizontal layui-form" role="form" id="clazzForm"
                  action="${pageContext.servletContext.contextPath}/lession/add.do" method="post">
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="subName">课程名称</label>
                    <div class="col-sm-9">
                        <input type="text" name="subName" id="subName" placeholder="请输入课程名称"
                               class="col-xs-10 col-sm-5" lay-verify="subName">
                    </div>
                </div>


                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="score">平均分</label>
                    <div class="col-sm-9">
                        <input type="text" name="score" id="score" class="col-xs-10 col-sm-5"
                               placeholder="请输入平均分" value="0" readonly>
                    </div>
                </div>


                <div class="clearfix form-actions">
                    <div class="col-md-offset-3 col-md-9">
                        <button class="btn btn-info" lay-submit lay-filter="add">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            添加
                        </button>

                        &nbsp; &nbsp; &nbsp;
                        <button class="btn" type="reset">
                            <i class="ace-icon fa fa-undo bigger-110"></i>
                            重置
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </jsp:body>
    </lesson:page>
</body>
</html>

src/main/webapp/WEB-INF/views/kevin/lession/list.jsp
<%--
  Created by IntelliJ IDEA.
  User: Administrator
  Date: 2018/7/28
  Time: 8:11
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="bizLesson" uri="http://com.biz.lesson/tag/core" %>
<%@ taglib prefix="lesson" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html>
<head>
    <title>欢迎使用 LESSION 6</title>
</head>
<body>

<lesson:page title="">
    <jsp:attribute name="script">
        <link rel="stylesheet" href="${pageContext.servletContext.contextPath}/webjars/layui/2.3.0/css/layui.css">
        <script language="JavaScript"
                src="${pageContext.servletContext.contextPath}/webjars/layui/2.3.0/layui.all.js"></script>
        <script language="JavaScript"
                src="${pageContext.servletContext.contextPath}/static-resource/ace/assets/js/daterangepicker.min.js"></script>
        <script language="JavaScript">
            $(function () {
                layui.use(["table", "util", "layer", "laytpl"], function () {

                    var $table = layui.table;
                    var $utils = layui.util;
                    var $layer = layui.layer;
                    var $laytpl = layui.laytpl;
                    var $ = layui.$, active = {
                        reload: function () {
                            var demoReload = $('#demoReload');
                            $table.reload('lession', {
                                page: true,

                            });
                        }
                    };

                    $('.demoTable .layui-btn').on('click', function () {
                        var type = $(this).data('type');
                        active[type] ? active[type].call(this) : '';
                    });

                    //第一个实例
                    $table.render({
                        elem: '#lession',
                        height: 471,
                        //数据接口,
                        url: '${pageContext.servletContext.contextPath}/lession/list.do',
                        method: "post",
                        //开启分页
                        page: true,
                        //表头
                        cols: [[
                            {field: 'id', title: 'ID', align: 'center', width: 100,},
                            {field: 'subName', title: '科目名称', align: 'center', width: 150,},
                            {field: 'perNum', title: '选修人数', align: 'center', width: 150,},
                            {field: 'score', title: '平均分', align: 'center', width: 150,},
                            {field: 'right', title: '操作', toolbar: "#barDemo", align: 'center',}
                        ]],
                        done: function (res) {
                            /**
                             * 隐藏 id 列。
                             */
                            // $("[data-field='id']").css('display', 'none');
                            console.log(res);
                        }
                    });

                    $table.on("tool(lession)", function (obj) {
                        if (obj.event === "edit") {
                            console.log(obj.data.id);
                            window.location.href = "${pageContext.servletContext.contextPath}/lession/to/" + obj.data.id + "/edit.do";
                        }


                        if (obj.event === "del") {
                            var subName = obj.data.subName;
                            console.log(obj.data.id);
                            bootbox.confirm(
                                {
                                    size: "small",
                                    message: "确认删除 " + subName + " 吗?",
                                    buttons: {
                                        confirm: {
                                            label: '删除',
                                            className: 'btn-success'
                                        },
                                        cancel: {
                                            label: '取消',
                                            className: 'btn-danger'
                                        }
                                    },
                                    callback: function (result) {
                                        if (result === true) {
                                            $.ajax({
                                                url: "${pageContext.servletContext.contextPath}/lession/del.do",
                                                type: "post",
                                                data: {
                                                    id: obj.data.id,
                                                    _method: "DELETE",
                                                },
                                                dataType: 'json',
                                                success: function (res) {
                                                    if (res.code === 200) {
                                                        $('.demoTable .layui-btn').click();
                                                    }
                                                    if (res.code === 400) {
                                                        bootbox.alert("该课程已经被选了，不能删除");
                                                    }
                                                }
                                            });
                                        }
                                    }
                                }
                            );
                        }
                    });
                });
            });
        </script>
    </jsp:attribute>

    <jsp:body>
        <div>
            <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                <ul class="breadcrumb">
                    <li>
                        <i class="ace-icon fa fa-home home-icon"></i>
                        <a href="welcome.do"><spring:message code="common.homepage"/></a>
                    </li>

                    <li class="active"><spring:message code="lession.title.list"/></li>
                </ul>
            </div>
            <br>
            <a class="layui-btn layui-btn-sm3 layui-btn-radius layui-icon layui-icon-add-circle"
                href="${pageContext.servletContext.contextPath}/lession/to/0/add.do">添加</a>
            <div class="layui-row demoTable">
                <div class="input-group">
                    <button class="layui-btn layui-hide layui-icon layui-icon-search" data-type="reload"> 搜索
                    </button>
                </div>
            </div>


            <table id="lession" lay-filter="lession"></table>

            <script type="text/html" id="barDemo">
                <a class="layui-btn layui-btn-xs layui-btn-radius layui-icon layui-icon-edit" lay-event="edit">
                    编辑</a>
                <a class="layui-btn layui-btn-danger layui-btn-radius layui-btn-xs layui-icon layui-icon-delete"
                   lay-event="del">删除</a>
            </script>


        </div>
    </jsp:body>
</lesson:page>

</body>
</html>

src/main/webapp/WEB-INF/views/kevin/lession/modify.jsp
<%--
  Created by IntelliJ IDEA.
  User: Administrator
  Date: 2018/7/26
  Time: 13:40
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="bizLesson" uri="http://com.biz.lesson/tag/core" %>
<%@ taglib prefix="lesson" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>欢迎使用 LESSION 6</title>
    <link rel="stylesheet" href="${pageContext.servletContext.contextPath}/webjars/layui/2.3.0/css/layui.css">
    <script language="JavaScript"
            src="${pageContext.servletContext.contextPath}/webjars/layui/2.3.0/layui.all.js"></script>
</head>
<body>
<lesson:page title="">
<jsp:attribute name="script">
        <script language="JavaScript">
            $(function () {
                layui.use(["upload", "form"], function () {
                    var $upload = layui.upload;
                    var $form = layui.form;
                    $form.render();

                    $form.verify({
                        subName: function (value, item) {
                            if (value.trim() === "") {
                                return "课程名称不能为空"
                            }
                        },
                    });

                    $form.on("submit(modify)", function (data) {
                        $.ajax({
                            url: data.form.action,
                            type: data.form.method,
                            data: data.field,
                            dataType: "json",
                            success: function (res) {
                                console.log(res);
                                if (res.code === 400) {
                                }
                                if (res.code === 200) {
                                    window.location.href = "${pageContext.servletContext.contextPath}/lession/to/0/list.do";
                                }
                            }
                        });
                        return false;
                    });
                });
            });
        </script>
    </jsp:attribute>

<jsp:body>
<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="welcome.do"><spring:message code="common.homepage"/></a>
        </li>

        <li class="active"><spring:message code="clazz.title.edit"/></li>
    </ul>
</div>
<br><br>
<div class="container">
    <div id="user-profile-1" class="user-profile row">

        <div class="col-sm-9">
            <form class="form-horizontal layui-form" role="form" id="clazzForm"
                  action="${pageContext.servletContext.contextPath}/lession/modify.do" method="post">
                <div class="form-group">
                    <input type="hidden" name="_method" value="PUT">
                    <label class="col-sm-3 control-label no-padding-right" for="subName">课程名称</label>
                    <div class="col-sm-9">
                        <input type="text" name="subName" id="subName" placeholder="请输入课程名称"
                               class="col-xs-10 col-sm-5" value="${lession.subName}" lay-verify="subName">
                    </div>
                </div>

                <input type="hidden" name="id" value="${lession.id}">
                <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="score">平均分</label>
                    <div class="col-sm-9">
                        <input type="text" name="score" id="score" class="col-xs-10 col-sm-5"
                               placeholder="请输入平均分" value="${lession.score}" readonly>
                    </div>
                </div>


                <div class="clearfix form-actions">
                    <div class="col-md-offset-3 col-md-9">
                        <button class="btn btn-info" lay-submit lay-filter="modify">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            修改
                        </button>

                        &nbsp; &nbsp; &nbsp;
                        <button class="btn" type="reset">
                            <i class="ace-icon fa fa-undo bigger-110"></i>
                            重置
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    </jsp:body>
    </lesson:page>
</body>
</html>